### ISSUE TITLE
Support for term splitting in WP 4.2

### ISSUE THREAD

**Issue by nickdaugherty** [voceconnect/objects-to-objects#10]
https://href.li/?https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/

Anywhere term ids are stored or cached could have problems if a term is split (as part of 4.2).

The plugin should clear any caches on the `split_shared_term` action, or otherwise move to a caching model that includes a TTL to allow expiration and regenration (instead of caching indefinitely, which is how it's done now).

Some parts of this plugin can't easily be invalidated upon splitting a term, and will require a cache TTL to address this issue.

**Comment by prettyboymp** [comment]
fixed in #1f53f8bda9b
