### ISSUE TITLE
Plugin is not writing to database

### ISSUE THREAD

**Issue by wilson428** [voceconnect/objects-to-objects#12]
I'm having a strange issue where I will setup connections between objects using this plugin, but they will disappear within 24 hours. This seems to suggest that the connections are being stored in memcache but not the database. Has anyone seen this happen before?

**Comment by wilson428** [comment]
I suggested a fix for this in PR #13. The issue is that my content had existing values for `o2o_term_id` in the metadata, so when I imported my content to a production instance, o2o wasn't able to overwrite them with new values. It was able to make the associations in the cache, which is why my changes kept vanishing!

**Comment by prettyboymp** [comment]
fixed in f6ee276
