### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Post_Selection_UI' not found

### ISSUE THREAD

**Issue by hellodev-maxim** [voceconnect/objects-to-objects#18]
Fatal error: Uncaught Error: Class 'Post_Selection_UI' not found in /srv/www/wordpress-default/wp-content/mu-plugins/shared-plugins/objects-to-objects/admin/admin.php:15 
Stack trace: 
#0 /srv/www/wordpress-default/wp-content/mu-plugins/shared-plugins/objects-to-objects/src/o2o.php(64): O2O_Admin->init()
#1 /srv/www/wordpress-default/wp-includes/plugin.php(524): O2O->init('')
#2 /srv/www/wordpress-default/wp-settings.php(411): do_action('init')
#3 /srv/www/wordpress-default/wp-config.php(53): require_once('/srv/www/wordpr...')
#4 /srv/www/wordpress-default/wp-load.php(39): require_once('/srv/www/wordpr...')
#5 /srv/www/wordpress-default/wp-admin/admin.php(31): require_once('/srv/www/wordpr...')
#6 /srv/www/wordpress-default/wp-admin/index.php(10): require_once('/srv/www/wordpr...')
#7 {main} thrown in /srv/www/wordpress-default/wp-content/mu-plugins/shared-plugins/objects-to-objects/admin/admin.php on line 15

This is the line that instantiates a Post_Selection_UI class, which, as far as I understand has been removed in a previous commit:
https://github.com/voceconnect/objects-to-objects/commit/cdd4183d5a3b25e35a7901848029e25c9d63b3f3

**Comment by matgargano** [comment]
I haven't touched this project in forever, but looking at that commit it looks like @prettyboymp removed Post Selection UI as a submodule (dependency) and it is now brought in via composer.

Try running `composer install` in the directory of the o2o plugin and it should bring the dependency in.

**Comment by matgargano** [comment]
I haven't touched this project in forever, but looking at that commit it
looks like @prettyboymp removed Post Selection UI as a submodule
(dependency) and it is now brought in via composer.

Try running `composer install` in the directory of the o2o plugin and it
should bring the dependency in.
