### ISSUE TITLE
Import/Export issue

### ISSUE THREAD

**Issue by markparolisi** [voceconnect/objects-to-objects#3]
Can you please test exporting connected objects and importing them to another install? We assumed this would work since O2O uses taxonomies as its glue, but the post ID mappings are coming back incorrect after import and the connection does not allow for the creation of new relationships after the import has occurred.

**Comment by wilson428** [comment]
I think #13 addresses this.

**Comment by wilson428** [comment]
FWIW: As a quick-and-dirty fix to the import problem, I just cleared out all the o2o meta keys and started over. Not an option for a huge site, but wasn't a big deal for me.

```delete_post_meta_by_key("o2o_term_id");```
