### ISSUE TITLE
Undocumented dependency on post-selection-ui

### ISSUE THREAD

**Issue by wilson428** [voceconnect/objects-to-objects#9]
I wasn't able to get this working until I manually cloned [`post-selection-ui`](https://github.com/voceconnect/post-selection-ui) into the admin folder. Looks like it used to be there by default but then was moved out. Should this be a step in the README?

**Comment by prettyboymp** [comment]
The dependency on the post-selection-ui was migrated from being fulfilled via git submodules to being fulfilled with composer.  This allowed better version management when dealing with a project using multiple libraries that depended on the post-selection-ui.

**Comment by wilson428** [comment]
Oh duh, I just cloned. Might be a good idea to include the composer command for people like me. Closing. Thanks!
